spring:
  application:
    name: spring-langchain4j

google:
  gemini:
    api-key: # from env

groq:
  api-key: # from env

langchain4j:
  open-ai:
    chat-model:
      api-key: # from env variable
      model-name: gpt-4o
      log-requests: true
      log-responses: true
